import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/pages/home.module.css'
import Header from '@/lib/components/shared/header'
import { Input } from '@/lib/components/shared'
import ProductCard from '@/lib/components/shared/product-card'
import { useEffect, useState } from 'react'
import { SearchResult } from '@/lib/models/search.model'
import { useDebounce } from '@/lib/hooks/use-debounce'
import ProductList from '@/lib/components/shared/product-list'
import { useProductsList } from '@/lib/contexts/product-list/product-list.hooks'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { products, refetch, onFiltersChange } = useProductsList()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header>
          <form
            onSubmit={(event) => {
              event.preventDefault()
              refetch()
            }}
          >
            <Input
              name="q"
              type="search"
              endAdornment
              onChange={onFiltersChange}
            />
          </form>
        </Header>
        {!!(products.size > 0) && (
          <section className={styles.productListSection}>
            <div className={styles.productListWrapper}>
              <ProductList products={products} />
            </div>
          </section>
        )}
      </main>
    </>
  )
}
